Errors and timeout
brightec/rxp-ios pull request #7
Opened 2020-02-20 15:35 UTC by jonnytownend

### In this PR:
- One of the optional `HPPViewControllerDelegate` method implementations in `HPPManager` had an incorrect parameter type, and therefore didn't conform to the delegate protocol. When the expected method was called from `HPPViewController`, it was force-unwrapped and found to be `nil`, causing a crash. The method parameter has been updated.
- A delay has been added when dismissing `HPPViewController`, to ensure that the view controller is always dismissed after it has been presented.
- The webview in `HPPViewController` is now setup on `viewWillAppear` instead of `viewDidLoad`. This ensures that the user will not see the previous state of the webview (including a CVV code that may have been perviously entered).
- When tapping the 'Pay Now' button, a JavaScript timeout has been added to ensure that the screen doesn't hang (previously, if the network call failed, the screen would hang).

### Still to do:
- Implement a retry mechanism for the `/callback/globalpayments` call.

2020-02-20 16:14 UTC, thompsondave requested changes

2020-02-20 16:14 UTC, thompsondave commented on Pod/Classes/RealexComponent/HPPManager.swift
>          self.delegate?.HPPManagerFailedWithError!(error as NSError?)
Do you need this cast anymore?

2020-02-20 16:34 UTC, jonnytownend commented on Pod/Classes/RealexComponent/HPPManager.swift
>          self.delegate?.HPPManagerFailedWithError!(error as NSError?)
No I guess not. Done.

2020-02-21 07:59 UTC, thompsondave approved these changes
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/brightec/rxp-ios/7)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-02-21 07:59 UTC, merged